version: "3"
services:
  gh-sg-kotlin-test:
    build:
      context: .
    networks:
      - hmpps
    container_name: gh-sg-kotlin-test
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      # TODO: Remove this URL and replace with outgoing service URLs
      - EXAMPLE_URL=http://gh-sg-kotlin-test:8080
      - SPRING_PROFILES_ACTIVE=dev

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

networks:
  hmpps:
